---

- hosts: all

  tasks:
  - name: Remove chrony on Ubuntu targets if installed
    apt:
      name: chrony
      state: absent
    when: ansible_os_family == "Debian"

  - name: Install ntp on Ubuntu targets if installed
    apt:
      name: ntp
      state: latest
    when: ansible_os_family == "Debian"

  - name: Remove chrony on RedHat targets if installed
    yum:
      name: chrony
      state: absent
    when: ansible_os_family == "RedHat"

  - name: Install ntp on CentOS targets if installed
    yum:
      name: ntp
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Push the NTP config to Ubuntu
    template:
      src=ntp-template.j2
      dest=/etc/ntp.conf
      owner=root
      group=root
      mode=0644
      backup=yes
    when: ansible_os_family == "Debian"
    notify: start_restart_ntp_client_ubuntu

  - name: Push the NTP config to RedHat
    template:
      src=ntp-template.j2
      dest=/etc/ntp.conf
      owner=root
      group=root
      mode=0644
      backup=yes
    when: ansible_os_family == "RedHat"
    notify: start_restart_ntp_client_redhat

  handlers:

  # This is to ensure that NTP is started
  - name: start_restart_ntp_client_ubuntu
    service:
      name=ntp
      state=restarted
      enabled=yes

  - name: start_restart_ntp_client_redhat
    service:
      name=ntpd
      state=restarted
      enabled=yes
