---

- hosts: webservers
  vars:
    http_port: 80
  remote_user: root

  tasks:
  - name: Install Apache webserver on Ubuntu hosts
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: Install Apache webserver on CentoOS hosts
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Enable & start Apache webserver on Ubuntu hosts
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: Enable & start Apache webserver on RedHat hosts
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

- hosts: ansible_class_centos7_1
  gather_facts: no

  tasks:
  - name: Install MongoDB on ansible_class_centos7_1
    yum:
      name: mongodb-server
      state: present
    notify:
      start mongodb

  handlers:
  - name: start mongodb
    service:
      name: mongod
      state: started

- hosts: ansible_class_ubuntu_1
  gather_facts: no

  tasks:
  - name: Install MongoDB on ansible_class_ubuntu_1
    apt:
      update_cache: yes
      name: mysql-server
      state: latest

  - name: Get MySQL Status
    shell: service mysql status >> ~/mysqlstatus.txt
    args:
      warn: no
    ignore_errors: yes
    tags:
      - mysqlstatus

  - name: Deliver MySQL Status
    fetch:
      src: ~/mysqlstatus.txt
      dest: fetched_status.txt
      flat: yes
    tags: 
      - mysqlstatus

  handlers:
  - name: start mongodb
    service:
      name: mongod
      state: started


